# 构建阶段
FROM rust:alpine3.22 AS builder

# Alpine下需要安装musl-dev来构建（如果你依赖一些C库的话）
#RUN apk add --no-cache musl-dev
#RUN apk add --no-cache protobuf-compiler
#    protoc \
#    protobuf-dev \

# 安装 protoc 和其他构建依赖
RUN apk add --no-cache \
    libgcc \
    build-base \
    musl-dev \
    openssl-dev \
    openssl-libs-static \
    postgresql-dev

# 验证安装
#RUN protoc --version
#FROM rust:1.91.1-slim-bookworm AS builder
#ENV RUSTFLAGS="-C target-feature=+crt-static -C link-arg=-lm -C link-arg=-lgcc"

#RUN apt-get update && apt-get install -y \
#    pkg-config libssl-dev musl-tools libpq-dev && \
#    rm -rf /var/lib/apt/lists/* && \
#    ln -sf /usr/bin/musl-gcc /usr/local/bin/x86_64-linux-musl-gcc

ARG APP_NAME
ARG FEATURES
RUN echo ${FEATURES}

WORKDIR /app

COPY . .

RUN cargo build -p laurel-${APP_NAME} --release ${FEATURES}

# 运行时阶段
FROM alpine:latest
ENV TZ=Asia/Shanghai
RUN apk add --no-cache libgcc tzdata ca-certificates && \
    ln -sf /usr/share/zoneinfo/${TZ} /etc/localtime
#libpq5 \
#FROM debian:bookworm-slim
#RUN apt-get update && apt-get install -y \
#    libgcc-s1 \
#    ca-certificates \
#    && rm -rf /var/lib/apt/lists/*

ARG APP_NAME

# 创建非root用户
RUN addgroup -S app && adduser -S app -G app
#RUN groupadd -r app && useradd -r -g app -s /bin/false app


USER app
WORKDIR /app
RUN mkdir config

COPY --from=builder /app/target/release/laurel-${APP_NAME} /app/app
COPY --from=builder /app/${APP_NAME}/config/ ./config/
#CMD ["./app $OPTIONS"]
CMD ["/bin/sh", "-c", "exec /app/app $OPTIONS"]